INSERT INTO prod.iyiye.kit-category value {'name' : 'burger', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/burger.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'chicken', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/chicken.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'gluten-free', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/gluten-free.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'halal', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/halal.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'jhatka', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/jhatka.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'kosher', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/kosher.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'nut-free', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/nut-free.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'raw', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/raw.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'sea-food', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/sea-food.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'thai', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/thai.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'vegan', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/vegan.jpg'}
INSERT INTO prod.iyiye.kit-category value {'name' : 'vegetarian', 'imageUrl' : 'https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/vegetarian.jpg'}