/*
INSERT IGNORE INTO notif.in_app_notifications (`type`, `receiver_username`, `body`) VALUES
    ('announcement', 'vahdet', 'This is gospel, this is a test');
*/

INSERT IGNORE INTO portf.category (`name`,`image_url`) VALUES 
    ('burger','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/burger.jpg'),
    ('chicken','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/chicken.jpg'),
    ('dessert','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/dessert.jpg'),
    ('glutenFree','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/gluten-free.jpg'),
    ('halal','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/halal.jpg'),
    ('jhatka','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/jhatka.jpg'),
    ('keto','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/keto.jpg'),
    ('kosher','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/kosher.jpg'),
    ('noAddedSugar','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/no-added-sugar.jpg'),
    ('nutFree','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/nut-free.jpg'),
    ('noCook','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/no-cook.jpg'),
    ('seaFood','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/sea-food.jpg'),
    ('thai','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/thai.jpg'),
    ('vegan','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/vegan.jpg'),
    ('vegetarian','https://iyiye-meta-files.s3-eu-west-1.amazonaws.com/images/category/vegetarian.jpg');

/* Vegetable * Fruit (with PLU codes)*/
INSERT IGNORE INTO portf.ingredient (`code`,`category`,`name_en`,`size`,`unit`) VALUES
    ('3000','fruit','Alkmene Apple',NULL,NULL),
    ('3001','fruit','Aurora/Southern Rose Apple','small',NULL),
    ('3002','fruit','Cantared Apple',NULL,NULL),
    ('3003','fruit','D''Estivale Apple',NULL,NULL),
    ('3004','fruit','Discovery Apple',NULL,NULL),
    ('3005','fruit','Golden Delicious Blush Apple',NULL,NULL),
    ('3006','fruit','Ingrid Marie Apple',NULL,NULL),
    ('3007','fruit','Lochbuie Apple',NULL,NULL),
    ('3008','fruit','Rubinette Apple',NULL,NULL),
    ('3009','fruit','Russet Apple',NULL,NULL),
    ('3010','fruit','Cripps Red Apple','small',NULL),
    ('3011','fruit','Worcester Apple',NULL,NULL),
    ('3012','fruit','Abate Fetel Pear',NULL,NULL),
    ('3013','fruit','Beurre Hardy Pear',NULL,NULL),
    ('3014','fruit','Bon Rouge Pear',NULL,NULL),
    ('3015','fruit','Clara Friis Pear',NULL,NULL),
    ('3016','fruit','Concorde Pear',NULL,NULL),
    ('3017','fruit','Conference Pear',NULL,NULL),
    ('3018','fruit','Durondeau Pear',NULL,NULL),
    ('3019','fruit','Flamingo Pear',NULL,NULL),
    ('3020','fruit','General Leclerc Pear',NULL,NULL),
    ('3021','fruit','Guyot Pear',NULL,NULL),
    ('3022','fruit','Josephine Pear',NULL,NULL),
    ('3023','fruit','Passe Crassane Pear','small',NULL),
    ('3024','fruit','Rocha Pear',NULL,NULL),
    ('3025','fruit','Rosemarie Pear',NULL,NULL),
    ('3026','fruit','Triumph De Vienne Pear',NULL,NULL),
    ('3027','fruit','Shamouti Orange',NULL,NULL),
    ('3028','fruit','Delta Seedless Orange','small',NULL),
    ('3029','fruit','Satsuma Tangerine',NULL,NULL),
    ('3030','fruit','Nova Tangerine',NULL,NULL),
    ('3031','fruit','Jamaican Tangor Tangerine',NULL,NULL),
    ('3032','fruit','Ellendale Tangerine',NULL,NULL),
    ('3033','fruit','Charentais Melon','small',NULL),
    ('3034','fruit','Charentais Melon','large',NULL),
    ('3035','fruit','White Flesh Nectarine','large',NULL),
    ('3036','fruit','Midknight Orange','small',NULL),
    ('3037','fruit','Queen Pineapple',NULL,NULL),
    ('3038','fruit','Granadilla Passion Fruit',NULL,NULL),
    ('3039','fruit','Physalis',NULL,NULL),
    ('3040','fruit','Red Pitaya',NULL,NULL),
    ('3041','fruit','Rambutan',NULL,NULL),
    ('3042','fruit','Mangosteen',NULL,NULL),
    ('3043','fruit','Italia Seeded Grape',NULL,'bunch'),
    ('3044','fruit','Black Velvet Apricot',NULL,NULL),
    ('3045','fruit','On Branch Date',NULL,NULL),
    ('3046','fruit','Frozen Date',NULL,NULL),
    ('3047','fruit','Medjool Date',NULL,NULL),
    ('3048','vegetable','Flat Bean',NULL,NULL),
    ('3049','vegetable','Fine Bean',NULL,NULL),
    ('3050','vegetable','Winter White Cabbage',NULL,NULL),
    ('3051','vegetable','Spring Green Cabbage',NULL,NULL),
    ('3052','vegetable','String Garlic',NULL,NULL),
    ('3053','vegetable','Baby Parsnip',NULL,NULL),
    ('3054','vegetable','Elongated Clovis/Lamuyo Red Pepper',NULL,NULL),
    ('3055','vegetable','Elongated Clovis/Lamuyo Green Pepper',NULL,NULL),
    ('3056','vegetable','Elongated Clovis/Lamuyo Yellow Pepper',NULL,NULL),
    ('3057','vegetable','Elongated Clovis/Lamuyo Orange Pepper',NULL,NULL),
    ('3058','vegetable','Elongated Clovis/Lamuyo White Pepper',NULL,NULL),
    ('3059','vegetable','Crown Prince Squash',NULL,NULL),
    ('3060','vegetable','Vegetable Marrow Squash',NULL,NULL),
    ('3061','vegetable','Beefsteak Tomato',NULL,NULL),
    ('3062','herb','Bay Leave',NULL,NULL),
    ('3063','herb','Fennel Leave',NULL,NULL),
    ('3064','herb','Aloe Vera Leave',NULL,NULL),
    ('3065','fruit','Cameo Apple','small',NULL),
    ('3066','fruit','Cameo Apple','large',NULL),
    ('3067','fruit','Swiss Gourmet Apple','small',NULL),
    ('3068','fruit','Swiss Gourmet Apple','large',NULL),
    ('3069','fruit','Gravenstein Red Apple','small',NULL),
    ('3070','fruit','Gravenstein Red Apple','large',NULL),
    ('3071','fruit','Granny Smith Red Apple',NULL,NULL),
    ('3072','fruit','Lady Apple',NULL,NULL),
    ('3073','fruit','Macoun Apple',NULL,NULL),
    ('3074','fruit','Greening Apple',NULL,NULL),
    ('3075','fruit','Baldwin Apple',NULL,NULL),
    ('3076','fruit','Melrose Apple',NULL,NULL),
    ('3077','fruit','Northern Spy Apple',NULL,NULL),
    ('3078','fruit','Liberty Apple',NULL,NULL),
    ('3079','vegetable','Purple Asparagus',NULL,NULL),
    ('3080','fruit','Pinkerton Avocado',NULL,NULL),
    ('3081','fruit','Saskatoon Berry',NULL,NULL),
    ('3082','vegetable','Crowns Broccoli',NULL,NULL),
    ('3083','vegetable','Stalk Brussels Sprout',NULL,NULL),
    ('3084','herb','Chervil',NULL,NULL),
    ('3085','vegetable','Indian Decorative Corn','large',NULL),
    ('3086','vegetable','Indian Decorative Corn','mini',NULL),
    ('3087','vegetable','Indian Strawberry Corn',NULL,NULL),
    ('3088','fruit','Red Currant',NULL,NULL),
    ('3089','vegetable','Chinese Eggplant',NULL,NULL),
    ('3090','vegetable','Thai Eggplant',NULL,NULL),
    ('3091','vegetable','Gobo Root',NULL,NULL),
    ('3092','fruit','Oroblanco',NULL,NULL),
    ('3093','fruit','Grape',NULL,NULL),
    ('3094','fruit','Grape',NULL,NULL),
    ('3095','vegetable','Multicolor Kale',NULL,NULL),
    ('3096','vegetable','Kohlrabi',NULL,NULL),
    ('3097','vegetable','Romaine Red Lettuce',NULL,NULL),
    ('3098','vegetable','Boston Red Lettuce',NULL,NULL),
    ('3099','vegetable','Lotus Root',NULL,NULL),
    ('3100','fruit','Gold Honeydew Melon',NULL,NULL),
    ('3101','fruit','Piel De Sapo Melon',NULL,NULL),
    ('3102','vegetable','Morel Mushroom',NULL,'gram'),
    ('3103','vegetable','Enoki Mushroom',NULL,'gram'),
    ('3104','fruit','Roho 3615 Apple',NULL,NULL),
    ('3105','nut','Cashew',NULL,NULL),
    ('3106','nut','Macadamia',NULL,NULL),
    ('3107','fruit','Navel Orange','medium',NULL),
    ('3108','fruit','Valencia Orange','medium',NULL),
    ('3109','fruit','Seville (Marmalade Type) Orange',NULL,NULL),
    ('3110','fruit','Cara Cara Navel Orange',NULL,NULL),
    ('3111','fruit','Red-Fleshed Papaya',NULL,NULL),
    ('3112','fruit','Meridol Papaya',NULL,NULL),
    ('3113','fruit','Flat White Flesh Peach',NULL,NULL),
    ('3114','fruit','Green Mango','extra large',NULL),
    ('3115','fruit','Flat Yellow Flesh Peach',' NULL',NULL),
    ('3116','fruit','Yellow Flesh Peach','small',NULL),
    ('3117','fruit','Yellow Flesh Peach','large',NULL),
    ('3118','fruit','Starkrimson Pear',NULL,NULL),
    ('3119','vegetable','Greenhouse Green Bell Pepper','small',NULL),
    ('3120','vegetable','Greenhouse Green Bell Pepper','large',NULL),
    ('3121','vegetable','Greenhouse Orange Bell Pepper',NULL,NULL),
    ('3122','vegetable','Greenhouse White Bell Pepper',NULL,NULL),
    ('3123','vegetable','Greenhouse Brown Bell Pepper',NULL,NULL),
    ('3124','vegetable','Greenhouse Purple Bell Pepper',NULL,NULL),
    ('3125','vegetable','Habanero Pepper',NULL,NULL),
    ('3126','fruit','Plumcot',NULL,NULL),
    ('3127','fruit','Pomegranate','medium',NULL),
    ('3128','vegetable','Purple Potato',NULL,NULL),
    ('3129','fruit','Pummelo',NULL,NULL),
    ('3130','vegetable','Jumbo Pumpkin',NULL,NULL),
    ('3131','vegetable','Decorative Pumpkin',NULL,NULL),
    ('3132','vegetable','White Pumpkin',NULL,NULL),
    ('3133','vegetable','White Mini Pumpkin',NULL,NULL),
    ('3134','vegetable','Pie Pumpkin Pumpkin',NULL,NULL),
    ('3135','vegetable','Ornamental Gourd',NULL,NULL),
    ('3136','fruit','Sapodilla',NULL,NULL),
    ('3137','fruit','White Sapote',NULL,NULL),
    ('3138','fruit','Black Sapote',NULL,NULL),
    ('3139','herb','Savory',NULL,NULL),
    ('3140','vegetable','Cucuzza Squash',NULL,NULL),
    ('3141','vegetable','Opo Squash',NULL,NULL),
    ('3142','vegetable','Carnival Squash',NULL,NULL),
    ('3143','vegetable','Acorn - Baby Squash',NULL,NULL),
    ('3144','fruit','Fall Glo Tangerine',NULL,NULL),
    ('3145','vegetable','Roma Tomato',NULL,NULL),
    ('3146','vegetable','Red Cherry Tomato',NULL,NULL),
    ('3147','vegetable','Yellow Cherry  Tomato',NULL,NULL),
    ('3148','vegetable','Yellow Regular Tomato',NULL,NULL),
    ('3149','vegetable','Orange Regular Tomato',NULL,NULL),
    ('3150','vegetable','Red Cocktail Tomato',NULL,NULL),
    ('3151','vegetable','Red Regular Tomato','large',NULL),
    ('3152','fruit','Melogold Grapefruit',NULL,NULL),
    ('3153','fruit','Delta Seedless Orange','medium',NULL),
    ('3154','fruit','Delta Seedless Orange','large',NULL),
    ('3155','fruit','Midknight Orange','medium',NULL),
    ('3156','fruit','Midknight Orange','large',NULL),
    ('3157','fruit','White Grapefruit','extra large',NULL),
    ('3158','fruit','White Grapefruit','extra large',NULL),
    ('3159','fruit','White Grapefruit','extra large',NULL),
    ('3160','vegetable','Chinese Broccoli',NULL,NULL),
    ('3161','vegetable','Baby Chinese Mustard',NULL,NULL),
    ('3162','vegetable','Water Spinach',NULL,NULL),
    ('3163','vegetable','Shanghai Pak Choi',NULL,NULL),
    ('3164','vegetable','Yu Choy',NULL,NULL),
    ('3165','vegetable','Treviso Radicchio',NULL,NULL),
    ('3166','vegetable','Tuscan Cabbage',NULL,NULL),
    ('3167','vegetable','Frisee',NULL,NULL),
    ('3168','vegetable','Castlefranco Radicchio',NULL,NULL),
    ('3169','vegetable','Catalogna Lettuce',NULL,NULL),
    ('3271','fruit','Virginia Gold Apple',NULL,NULL),
    ('3272','fruit','Sommerfeld Apple',NULL,NULL),
    ('3273','vegetable','Golden Beet',NULL,NULL),
    ('3274','fruit','Fresh Prune',NULL,NULL),
    ('3275','vegetable','Yellow Ñame',NULL,NULL),
    ('3276','vegetable','White Ñame',NULL,NULL),
    ('3277','vegetable','Baby Broccoli',NULL,NULL),
    ('3278','fruit','Plumcot',NULL,NULL),
    ('3279','fruit','Golden Kiwifruit',NULL,NULL),
    ('3280','fruit','Regular Kiwifruit','jumbo',NULL),
    ('3281','fruit','Orange Seedless Watermelon',NULL,NULL),
    ('3282','vegetable','Roma Tomato',NULL,NULL),
    ('3283','fruit','Honeycrisp Apple','large',NULL),
    ('3284','fruit','Red Delicious Apple','extra large',NULL),
    ('3285','fruit','Golden Delicious Apple','extra large',NULL),
    ('3286','vegetable','Sweet Red Italian Flat Onion',NULL,NULL),
    ('3287','fruit','Hawaiian Plantain Banana',NULL,NULL),
    ('3288','vegetable','Sweet Potato',NULL,NULL),
    ('3289','fruit','Sprite Melon',NULL,NULL),
    ('3290','fruit','Aurora Apple','large',NULL),
    ('3291','fruit','Belle De Boskoop Apple','small',NULL),
    ('3292','fruit','Belle De Boskoop Apple','large',NULL),
    ('3293','fruit','Scifresh Apple','small',NULL),
    ('3294','fruit','Scifresh Apple','large',NULL),
    ('3295','fruit','Sciearly Apple','small',NULL),
    ('3296','fruit','Sciearly Apple','large',NULL),
    ('3297','fruit','Scired Apple',NULL,NULL),
    ('3298','fruit','Redfield Apple',NULL,NULL),
    ('3299','fruit','Sonya Apple','small',NULL),
    ('3300','fruit','Sonya Apple','large',NULL),
    ('3301','fruit','Cripps Red Apple','large',NULL),
    ('3302','fruit','Regular Apricot','large',NULL),
    ('3303','fruit','Babaco',NULL,NULL),
    ('3304','fruit','Loganberries Berry',NULL,NULL),
    ('3305','fruit','Black Currant',NULL,NULL),
    ('3306','fruit','Charentais Melon','medium',NULL),
    ('3307','fruit','Charentais Melon','extra large',NULL),
    ('3308','fruit','Orange Seedless Watermelon ',NULL,NULL),
    ('3309','fruit','Lima Orange',NULL,NULL),
    ('3310','fruit','Pera Orange',NULL,NULL),
    ('3311','fruit','Curuba Passion Fruit',NULL,NULL),
    ('3312','fruit','Granadilla',NULL,NULL),
    ('3313','fruit','White Flesh Peach','small',NULL),
    ('3314','fruit','White Flesh Peach','large',NULL),
    ('3315','fruit','Scilate Apple','small',NULL),
    ('3316','fruit','Carmen Pear',NULL,NULL),
    ('3317','fruit','Angelys Pear',NULL,NULL),
    ('3318','fruit','Passe Crassane Pear','large',NULL),
    ('3319','fruit','Yellow Pitahaya',NULL,NULL),
    ('3320','vegetable','Romanesco Cauliflower',NULL,NULL),
    ('3321','vegetable','Celery Root',NULL,NULL),
    ('3322','vegetable','Pak Choi Sum',NULL,NULL),
    ('3323','vegetable','Baby Pak Choi Sum',NULL,NULL),
    ('3324','vegetable','Red Escarole',NULL,NULL),
    ('3325','vegetable','Green Coral Lettuce',NULL,NULL),
    ('3326','vegetable','Red Coral Lettuce',NULL,NULL),
    ('3327','vegetable','Mignonette Lettuce',NULL,NULL),
    ('3328','vegetable','Mixed Small-Leaf Salad Lettuce',NULL,NULL),
    ('3329','vegetable','Green Oak Leaf Lettuce',NULL,NULL),
    ('3330','vegetable','Red Oak Leaf Lettuce',NULL,NULL),
    ('3331','vegetable','Red Fresh - Bunch Onion',NULL,NULL),
    ('3332','vegetable','Baby Spinach',NULL,NULL),
    ('3333','vegetable','Orangy White Flesh Sweet Potato','small',NULL),
    ('3334','vegetable','Orangy White Flesh Sweet Potato','large',NULL),
    ('3335','vegetable','Red Cocktail Tomato',NULL,NULL),
    ('3336','vegetable','Roma Cocktail Tomato',NULL,NULL),
    ('3337','dried_fruit','Dried Fig',NULL,NULL),
    ('3338','herb','Anise',NULL,NULL),
    ('3339','fruit','Chantecler Apple',NULL,NULL),
    ('3340','fruit','Golden Russet Apple',NULL,NULL),
    ('3341','fruit','Charles Ross Apple',NULL,NULL),
    ('3342','fruit','Delblush Apple',NULL,NULL),
    ('3343','fruit','Dessert Apple',NULL,NULL),
    ('3344','fruit','Gloster Apple','small',NULL),
    ('3345','fruit','Gloster Apple','large',NULL),
    ('3346','fruit','Holstein Apple',NULL,NULL),
    ('3347','fruit','Laxtons Fortune Apple',NULL,NULL),
    ('3348','fruit','Lord Lambourne Apple',NULL,NULL),
    ('3349','fruit','Michaelmas Red Apple',NULL,NULL),
    ('3350','fruit','Reine Des Reinettes Apple','small',NULL),
    ('3351','fruit','Reine Des Reinettes Apple','large',NULL),
    ('3352','fruit','Reinettes/Heritage Apple',NULL,NULL),
    ('3353','fruit','St Edmunds Pippin Apple',NULL,NULL),
    ('3354','fruit','Ready-To-Eat Avocado',NULL,NULL),
    ('3355','fruit','Strawberries',NULL,NULL),
    ('3356','fruit','Strawberries',NULL,NULL),
    ('3357','fruit','Regular Cherry','small',NULL),
    ('3358','fruit','Regular Cherry','large',NULL),
    ('3359','fruit','Chasselas Grape',NULL,NULL),
    ('3360','fruit','Muscat De Hambourg Grape',NULL,NULL),
    ('3361','fruit','Without Postharvest Treatment Grapefruit',NULL,NULL),
    ('3362','fruit','Without Postharvest Treatment Lemon',NULL,NULL),
    ('3363','fruit','Bowen & Kensington Pride Mango',NULL,NULL),
    ('3364','fruit','R2E2 Mango',NULL,NULL),
    ('3365','fruit','Ready-To-Eat Mango',NULL,NULL),
    ('3366','fruit','Madroño',NULL,NULL),
    ('3367','fruit','Glasshouse Melon',NULL,NULL),
    ('3368','fruit','Ogen Melon',NULL,NULL),
    ('3369','fruit','Nectavigne Nectarine',NULL,NULL),
    ('3370','fruit','Maltaise Orange',NULL,NULL),
    ('3371','fruit','Salustiana Orange',NULL,NULL),
    ('3372','fruit','Navelate Orange',NULL,NULL),
    ('3373','fruit','Navelina Orange',NULL,NULL),
    ('3374','fruit','Without Postharvest Treatment Orange',NULL,NULL),
    ('3375','fruit','De Vigne & Sanguine Peach',NULL,NULL),
    ('3376','fruit','Alexander Lucas Pear',NULL,NULL),
    ('3377','fruit','Louise Bonne Pear',NULL,NULL),
    ('3378','fruit','Santa Maria Pear',NULL,NULL),
    ('3379','fruit','Mini Pineapple',NULL,NULL),
    ('3380','fruit','Perola Pineapple',NULL,NULL),
    ('3381','fruit','Soursop',NULL,NULL),
    ('3382','fruit','Sugar Apple',NULL,NULL),
    ('3383','fruit','Clementine Tangerine','small',NULL),
    ('3384','fruit','Clementine Tangerine','medium',NULL),
    ('3385','fruit','Clementine Tangerine','large',NULL),
    ('3388','fruit','Satsuma -Clauselina Tangerine',NULL,NULL),
    ('3389','fruit','Satsuma Tangerine',NULL,NULL),
    ('3390','vegetable','Arracacha',NULL,NULL),
    ('3391','vegetable','Rouge Salambo Artichoke',NULL,NULL),
    ('3392','vegetable','Green Bunch Asparagus',NULL,NULL),
    ('3393','vegetable','White Bunch Asparagus',NULL,NULL),
    ('3394','vegetable','Purple Bunch Asparagus',NULL,NULL),
    ('3395','vegetable','Red Belgian Endive',NULL,NULL),
    ('3396','vegetable','Savoy Red Cabbage',NULL,NULL),
    ('3397','vegetable','Summer Cabbage',NULL,NULL),
    ('3398','vegetable','Chickpea',NULL,NULL),
    ('3399','vegetable','Regular Fresh/Semi-Dried Garlic',NULL,NULL),
    ('3400','vegetable','Regular Smoked Garlic',NULL,NULL),
    ('3401','vegetable','One-Clove Types Garlic',NULL,NULL),
    ('3402','vegetable','Regular Bunch Leek',NULL,NULL),
    ('3403','vegetable','Baby Bunch Leek',NULL,NULL),
    ('3404','vegetable','Cep Mushroom',NULL,NULL),
    ('3405','vegetable','Fairy Ring Champignon Mushroom',NULL,NULL),
    ('3406','vegetable','Grey Tricholoma Mushroom',NULL,NULL),
    ('3407','vegetable','Grisette Mushroom',NULL,NULL),
    ('3408','vegetable','Black Trumpet Mushroom',NULL,NULL),
    ('3409','vegetable','Pioppino Mushroom',NULL,NULL),
    ('3410','vegetable','Saffron Milk-Cap Mushroom',NULL,NULL),
    ('3411','vegetable','Sheep Polypore Mushroom',NULL,NULL),
    ('3412','vegetable','Yellow/Brown Fresh Bunch Onion',NULL,NULL),
    ('3413','vegetable','Tabasco Pepper',NULL,NULL),
    ('3414','vegetable','Baking White Potato',NULL,NULL),
    ('3415','vegetable','Baking Red Potato',NULL,NULL),
    ('3416','vegetable','Bunch Rhubarb',NULL,NULL),
    ('3417','vegetable','New Zealand Spinach',NULL,NULL),
    ('3418','vegetable','Zucchini/Courgette Round Squash',NULL,NULL),
    ('3419','herb','Borage',NULL,NULL),
    ('3420','fruit','Belle Du Jumet Pear',NULL,NULL),
    ('3421','fruit','Watermelon Mini Seedless Melon',NULL,NULL),
    ('3422','fruit','Interspecific Apricot',NULL,NULL),
    ('3423','vegetable','Heirloom  Tomato',NULL,NULL),
    ('3424','vegetable','Purple Beta Sweet Carrot',NULL,NULL),
    ('3425','fruit','Ellendale Tangerine','small',NULL),
    ('3426','fruit','Ellendale Tangerine','medium',NULL),
    ('3427','fruit','Ellendale Tangerine','large',NULL),
    ('3428','fruit','Hone Tangerine','small',NULL),
    ('3429','fruit','Honey Tangerine','medium',NULL),
    ('3430','fruit','Honey Tangerine','large',NULL),
    ('3431','fruit','Imperial Tangerine','small',NULL),
    ('3432','fruit','Imperial Tangerine','medium',NULL),
    ('3433','fruit','Imperial Tangerine','large',NULL),
    ('3434','fruit','Tosca Pear',NULL,NULL),
    ('3435','fruit','Pinova Apple',NULL,NULL),
    ('3436','vegetable','Orange Cauliflower',NULL,NULL),
    ('3437','fruit','Flat Yellow Nectarine',NULL,NULL),
    ('3438','fruit','Ambrosia Apple',NULL,NULL),
    ('3439','fruit','White Flesh Flat Nectarine',NULL,NULL),
    ('3440','fruit','Pomegranate','large',NULL),
    ('3441','vegetable','Butterkin Squash',' NULL',NULL),
    ('3442','fruit','New York 1 Apple',' NULL',NULL),
    ('3443','fruit','New York 2 Apple',' NULL',NULL),
    ('3444','fruit','Green Dragon Apple',' NULL',NULL),
    ('3445','fruit','Ds 3 Apple',' NULL',NULL),
    ('3446','vegetable','Kale Sprout',' NULL',NULL),
    ('3447','fruit','Ds 22 Apple',' NULL',NULL),
    ('3448','fruit','Tip Top Cherry',' NULL',NULL),
    ('3449','fruit','Sugrathirteen Grape',' NULL',NULL),
    ('3450','fruit','Sugranineteen Grape',' NULL',NULL),
    ('3451','fruit','Sugrathirtyfour Grape',' NULL',NULL),
    ('3452','fruit','Sugrathirtyfive Grape',' NULL',NULL),
    ('3453','vegetable','Galangal Root',' NULL',NULL),
    ('3454','fruit','Green Jackfruit',' NULL',NULL),
    ('3455','fruit','Yellow Jackfruit',' NULL',NULL),
    ('3456','fruit','Winter Melon',' NULL',NULL),
    ('3457','fruit','President Plum',' NULL',NULL),
    ('3458','vegetable','Orange Cherry Tomato',' NULL',NULL),
    ('3459','fruit','Shiny Red Perssimmon',' NULL',NULL),
    ('3460','fruit','Red Jonaprince Apple',' NULL',NULL),
    ('3461','fruit','Lady Williams Apple',' NULL',NULL),
    ('3462','herb','Chinese Chive',' NULL',NULL),
    ('3463','vegetable','Amaranth',' NULL',NULL),
    ('3464','fruit','B-74 Mango',' NULL',NULL),
    ('3465','vegetable','Stripy Bell Pepper',' NULL',NULL),
    ('3466','fruit','Cape Rose Pear',' NULL',NULL),
    ('3467','fruit','Regal 13-82 Apple',' NULL',NULL),
    ('3468','fruit','Honeycrisp Apple','small',NULL),
    ('3469','fruit','Sugrasixteen Grape',' NULL',NULL),
    ('3470','fruit','Red Small Seed Watermelon',' NULL',NULL),
    ('3471','vegetable','Baby Cactus Leave',' NULL',NULL),
    ('3472','herb','Sacred Pepper',' NULL',NULL),
    ('3473','herb','Epazote',' NULL',NULL),
    ('3474','vegetable','Saffron Sweet Potato',' NULL',NULL),
    ('3475','herb','Peppermint Mint',' NULL',NULL),
    ('3476','herb','Orange Tree Leaf',' NULL',NULL),
    ('3477','herb','Papalo',' NULL',NULL),
    ('3478','vegetable','Quelite',' NULL',NULL),
    ('3479','vegetable','Chipilin Leaf',' NULL',NULL),
    ('3480','vegetable','Pumpkin Vine',' NULL',NULL),
    ('3481','vegetable','Xpelon',' NULL',NULL),
    ('3482','herb','Rabbit Herb',' NULL',NULL),
    ('3483','herb','Purple Herb',' NULL',NULL),
    ('3484','fruit','Dalinette Apple',' NULL',NULL),
    ('3485','fruit','Harovin Sundown Pear',' NULL',NULL),
    ('3486','fruit','Cn121 Apple',' NULL',NULL),
    ('3487','fruit','Mn 55 Apple',' NULL',NULL),
    ('3488','fruit','Red Mango','extra large  ',NULL),
    ('3489','fruit','Cepuna Pear',NULL,NULL),
    ('3490','fruit','Maia 1 Apple',NULL,NULL),
    ('3491','fruit','Arra15 Grape',NULL,NULL),
    ('3492','fruit','Arra29 Grape',NULL,NULL),
    ('3493','vegetable','Tearless Sweet Onion',NULL,NULL),
    ('3494','fruit','Yellow Mini Seedless Watermelon',NULL,NULL),
    ('3495','fruit','Celina Pear',NULL,NULL),
    ('3496','fruit','Ifg Core Red Seedless Grape',NULL,NULL),
    ('3497','fruit','Ifg Core Black Seedless  Grape',NULL,NULL),
    ('3498','fruit','Ifg Core Green Seedless Grape',NULL,NULL),
    ('3499','fruit','Ifg Novelty Red Seedless Grape',NULL,NULL),
    ('3500','fruit','Ifg Novelty Black Seedless Grape',NULL,NULL),
    ('3501','fruit','Ifg Novelty Green Seedless Grape',NULL,NULL),
    ('3502','fruit','Arra27 Grape',NULL,NULL),
    ('3503','fruit','Arra28 Grape',NULL,NULL),
    ('3504','fruit','Arra30 Grape',NULL,NULL),
    ('3505','fruit','Arra32 Grape',NULL,NULL),
    ('3506','fruit','Sweet Scarlet Grape',NULL,NULL),
    ('3507','fruit','Wa 38 Apple',NULL,NULL),
    ('3508','fruit','Thomcord Grape',NULL,NULL),
    ('3509','fruit','Gem Avocado',NULL,NULL),
    ('3510','fruit','Ambrosia Apple','small',NULL),
    ('3511','fruit','Wa 2 Apple',NULL,NULL),
    ('3512','vegetable','Round Tomato',NULL,NULL),
    ('3513','fruit','Shinano Gold Apple',NULL,NULL),
    ('3514','fruit','Fengapi Apple',NULL,NULL),
    ('3515','ALL','Prema 153 Apple','small',NULL),
    ('3516','fruit','Prema 153 Apple','large',NULL),
    ('3517','fruit','Kiwifruit',NULL,NULL),
    ('3518','fruit','Oksana Pear',NULL,NULL),
    ('3519','fruit','R10-45 Apple',NULL,NULL),
    ('3520','vegetable','Sk-20 Onion',NULL,NULL),
    ('3521','fruit','Regal D5-100 Apple',NULL,NULL),
    ('3522','fruit','Hw624 Pear',NULL,NULL),
    ('3523','fruit','Sq 159 Apple',NULL,NULL),
    ('3600','fruit','Antares Apple',NULL,NULL),
    ('3601','fruit','Huaguan Apple',NULL,NULL),
    ('3602','fruit','Belgica Apple',NULL,NULL),
    ('3603','fruit','Minneiska Apple',NULL,NULL),
    ('3604','fruit','Emmons Apple',NULL,NULL),
    ('3605','fruit','Nicoter Apple',NULL,NULL),
    ('3606','fruit','Sweet Sensation Pear',NULL,NULL),
    ('3607','fruit','Mariri Red Apple',NULL,NULL),
    ('3608','fruit','Sciros Apple','large',NULL),
    ('3609','fruit','Red Plumcot',NULL,NULL),
    ('3610','fruit','Green Plumcot',NULL,NULL),
    ('3611','fruit','Black Plumcot',NULL,NULL),
    ('3612','fruit','Nicogreen Apple',NULL,NULL),
    ('3613','fruit','Fuji Brak Apple',NULL,NULL),
    ('3614','fruit','Red Apricot',NULL,NULL),
    ('3615','fruit','Civni Apple',NULL,NULL),
    ('3616','fruit','Scilate Apple','large',NULL),
    ('3617','fruit','Seedless Lemon',NULL,NULL),
    ('3618','fruit','Opal Apple',NULL,NULL),
    ('3619','fruit','Milwa Apple',NULL,NULL),
    ('3620','fruit','Plumac Apple',NULL,NULL),
    ('3621','fruit','Francis Mango',NULL,NULL),
    ('3622','fruit','Honey Green Melon',NULL,NULL),
    ('3623','fruit','Hami Melon',NULL,NULL),
    ('3624','fruit','Korean Melon',NULL,NULL),
    ('3625','fruit','Minnewashta Apple',NULL,NULL),
    ('3626','fruit','Meyer Lemon',NULL,NULL),
    ('3627','fruit','Prema17 Apple','large',NULL),
    ('3628','fruit','Prema280 Apple',NULL,NULL),
    ('3629','fruit','Civg198 Apple',NULL,NULL),
    ('3630','fruit','Co-Op 43 Apple',NULL,NULL),
    ('3631','vegetable','Pink Pumpkin',NULL,NULL),
    ('3632','fruit','Dekopon Tangerine',NULL,NULL),
    ('4011','fruit','Yellow Banana',NULL,NULL),
    ('4012','fruit','Navel Orange','large',NULL),
    ('4013','fruit','Navel Orange','small',NULL),
    ('4014','fruit','Valencia Orange','small',NULL),
    ('4014','fruit','Valencia Orange','small',NULL),
    ('4015','fruit','Red Delicious Apple','small',NULL),
    ('4016','fruit','Red Delicious Apple','large',NULL),
    ('4017','fruit','Granny Smith Apple','large',NULL),
    ('4018','fruit','Granny Smith Apple','large',NULL),
    ('4019','fruit','Mcintosh Apple','large',NULL),
    ('4020','fruit','Golden Delicious Apple','large',NULL),
    ('4021','fruit','Golden Delicious Apple','small',NULL),
    ('4022','fruit','White Seedless Grape',NULL,NULL),
    ('4023','fruit','Red Seedless Grape',NULL,NULL),
    ('4024','fruit','Bartlett Pear','small',NULL),
    ('4025','fruit','Anjou Pear','small',NULL),
    ('4026','fruit','Bosc Pear','small',NULL),
    ('4027','fruit','Red Grapefruit','small',NULL),
    ('4028','fruit','Strawberry',NULL,NULL),
    ('4029','fruit','Pineapple','small',NULL),
    ('4030','fruit','Regular Kiwifruit',NULL,NULL),
    ('4031','fruit','Red Watermelon',NULL,NULL),
    ('4032','fruit','Red Watermelon Seedless Melon',NULL,NULL),
    ('4033','fruit','Lemon','small',NULL),
    ('4034','fruit','White Honeydew Melon','large',NULL),
    ('4035','fruit','Yellow Flesh Nectarine','small',NULL),
    ('4036','fruit','Yellow Flesh Nectarine','large',NULL),
    ('4037','fruit','Yellow Flesh Peach','small',NULL),
    ('4038','fruit','Yellow Flesh Peach','large',NULL),
    ('4039','fruit','Black Plum','small',NULL),
    ('4040','fruit','Black Plum','large',NULL),
    ('4041','fruit','Red Plum','small',NULL),
    ('4042','fruit','Red Plum','large',NULL),
    ('4043','fruit','Yellow Flesh Ready-To-Eat Peach','small',NULL),
    ('4044','fruit','Yellow Flesh Ready-To-Eat Peach','large',NULL),
    ('4045','fruit','Regular Cherry',NULL,NULL),
    ('4046','fruit','Hass Avocado','small',NULL),
    ('4047','fruit','Red Grapefruit','small',NULL),
    ('4048','fruit','Regular Lime',NULL,NULL),
    ('4049','fruit','Cantaloupe Melon','small',NULL),
    ('4050','fruit','Cantaloupe Melon','large',NULL),
    ('4051','fruit','Red Mango','small',NULL),
    ('4052','fruit','Regular Papaya','small',NULL),
    ('4053','fruit','Lemon','large',NULL),
    ('4054','fruit','Raspberry',NULL,NULL),
    ('4055','fruit','Tangerine',NULL,NULL),
    ('4056','fruit','Black Seedless Grape',NULL,NULL),
    ('4057','fruit','Haralson Apple','small',NULL),
    ('4058','fruit','Haralson Apple','large',NULL),
    ('4060','vegetable','Broccoli',NULL,NULL),
    ('4061','vegetable','Iceberg Lettuce',NULL,NULL),
    ('4062','vegetable','Green Cucumber',NULL,NULL),
    ('4063','vegetable','Red Regular Tomato','small',NULL),
    ('4064','vegetable','Red Regular Tomato','large',NULL),
    ('4065','vegetable','Green Field Grown Bell Pepper','large',NULL),
    ('4066','vegetable','French Bean',NULL,NULL),
    ('4067','vegetable','Zucchini',NULL,NULL),
    ('4068','vegetable','Green Scallion',NULL,NULL),
    ('4069','vegetable','Green Cabbage',NULL,NULL),
    ('4070','vegetable','Bunch Celery','small',NULL),
    ('4071','vegetable','Bunch Celery','small',NULL),
    ('4072','vegetable','Russet Potato',NULL,NULL),
    ('4073','vegetable','Red Potato',NULL,NULL),
    ('4074','vegetable','Orangy Red Flesh Sweet Potato','small',NULL),
    ('4075','vegetable','Red Leaf Lettuce',NULL,NULL),
    ('4076','vegetable','Green Leaf Lettuce',NULL,NULL),
    ('4077','vegetable','White Sweet Corn',NULL,NULL),
    ('4078','vegetable','Yellow Sweet Corn',NULL,NULL),
    ('4079','vegetable','Cauliflower','small',NULL),
    ('4080','vegetable','Green Asparagus','small',NULL),
    ('4081','vegetable','Regular Eggplant',NULL,NULL),
    ('4082','vegetable','Red Onion',NULL,NULL),
    ('4083','vegetable','White Potato',NULL,NULL),
    ('4084','vegetable','Artichoke','large',NULL),
    ('4085','vegetable','Regular Mushroom','large',NULL),
    ('4086','vegetable','Yellow Zucchini',NULL,NULL),
    ('4087','vegetable','Roma Tomato',NULL,NULL),
    ('4088','vegetable','Red Field Grown Bell Pepper',NULL,NULL),
    ('4089','vegetable','Bunched Red Radish',NULL,NULL),
    ('4090','vegetable','Regular Spinach',NULL,NULL),
    ('4091','vegetable','White Sweet Potato',NULL,NULL),
    ('4092','vegetable','Chinese Snow Pea',NULL,NULL),
    ('4093','vegetable','Brown Onion','large',NULL),
    ('4094','vegetable','Bunch Carrot',NULL,NULL),
    ('4095','vegetable','Yellow Turnip',NULL,NULL),
    ('4096','fruit','Ginger Gold Apple','large',NULL),
    ('4097','fruit','Ginger Gold Apple','small',NULL),
    ('4098','fruit','Akane Apple','small',NULL),
    ('4099','fruit','Akane Apple','large',NULL),
    ('4100','fruit','Fireside Apple','small',NULL),
    ('4101','fruit','Braeburn Apple','small',NULL),
    ('4102','fruit','Fireside Apple','large',NULL),
    ('4103','fruit','Braeburn Apple','large',NULL),
    ('4104','fruit','Cortland Apple','small',NULL),
    ('4105','fruit','Cox Orange Pippin Apple',NULL,NULL),
    ('4106','fruit','Cortland Apple','large',NULL),
    ('4107','fruit','Crab Apple',NULL,NULL),
    ('4108','fruit','Crispin Apple','small',NULL),
    ('4109','fruit','Crispin Apple','small',NULL),
    ('4110','fruit','Crispin Apple','large',NULL),
    ('4111','fruit','Crispin Apple','large',NULL),
    ('4112','fruit','Regent Apple','small',NULL),
    ('4113','fruit','Criterion Apple','small',NULL),
    ('4114','fruit','Regent Apple','large',NULL),
    ('4115','fruit','Criterion Apple','large',NULL),
    ('4116','fruit','Early Apple','small',NULL),
    ('4117','fruit','Early Apple','small',NULL),
    ('4118','fruit','Early Apple','large',NULL),
    ('4119','fruit','Early Apple','large',NULL),
    ('4120','fruit','Fiesta Apple',NULL,NULL),
    ('4121','fruit','Elstar Apple','small',NULL),
    ('4122','fruit','Sciros Apple','small',NULL),
    ('4123','fruit','Elstar Apple','large',NULL),
    ('4124','fruit','Empire Apple','small',NULL),
    ('4125','fruit','Empire Apple','small',NULL),
    ('4126','fruit','Empire Apple','large',NULL),
    ('4127','fruit','Empire Apple','large',NULL),
    ('4128','fruit','Cripps Pink Apple','small',NULL),
    ('4129','fruit','Fuji Apple','small',NULL),
    ('4130','fruit','Cripps Pink Apple','large',NULL),
    ('4131','fruit','Fuji Apple','large',NULL),
    ('4132','fruit','Gala Apple','small',NULL),
    ('4133','fruit','Gala Apple','small',NULL),
    ('4134','fruit','Gala Apple','large',NULL),
    ('4135','fruit','Gala Apple','large',NULL),
    ('4136','fruit','Golden Delicious Apple','small',NULL),
    ('4137','fruit','Golden Delicious Apple','large',NULL),
    ('4138','fruit','Granny Smith Apple','small',NULL),
    ('4139','fruit','Granny Smith Apple','small',NULL),
    ('4140','fruit','Idared Apple','small',NULL),
    ('4141','fruit','Jonamac Apple','small',NULL),
    ('4142','fruit','Idared Apple','large',NULL),
    ('4143','fruit','Jonamac Apple','large',NULL),
    ('4144','fruit','Jonagold Apple','small',NULL),
    ('4145','fruit','Jonagold Apple','small',NULL),
    ('4146','fruit','Jonagold Apple','large',NULL),
    ('4147','fruit','Jonagold Apple','large',NULL),
    ('4148','fruit','Jonathan Apple','small',NULL),
    ('4149','fruit','Jonathan Apple','small',NULL),
    ('4150','fruit','Jonathan Apple','large',NULL),
    ('4151','fruit','Jonathan Apple','large',NULL),
    ('4152','fruit','Mcintosh Apple','small',NULL),
    ('4153','fruit','Mcintosh Apple','small',NULL),
    ('4154','fruit','Mcintosh Apple','large',NULL),
    ('4155','fruit','Paulared Apple','small',NULL),
    ('4156','fruit','Gravenstein Apple','small',NULL),
    ('4157','fruit','Paulared Apple','large',NULL),
    ('4158','fruit','Gravenstein Apple','large',NULL),
    ('4159','vegetable','Vidalia Onion',NULL,NULL),
    ('4160','fruit','Pippin Apple','small',NULL),
    ('4161','vegetable','Texas Sweet Onion',NULL,NULL),
    ('4162','fruit','Pippin Apple','large',NULL),
    ('4163','vegetable','Walla Walla Onion',NULL,NULL),
    ('4164','vegetable','Maui Onion',NULL,NULL),
    ('4165','vegetable','California Sweet Onion',NULL,NULL),
    ('4166','vegetable','Other Sweet Onion',NULL,NULL),
    ('4167','fruit','Red Delicious Apple','small',NULL),
    ('4168','fruit','Red Delicious Apple','large',NULL),
    ('4169','fruit','Rome Apple','small',NULL),
    ('4170','fruit','Rome Apple','small',NULL),
    ('4171','fruit','Rome Apple','large',NULL),
    ('4172','fruit','Rome Apple','large',NULL),
    ('4173','fruit','Royal Gala Apple','small',NULL),
    ('4174','fruit','Royal Gala Apple','large',NULL),
    ('4176','fruit','Southern Snap Apple',NULL,NULL),
    ('4177','fruit','Spartan Apple','small',NULL),
    ('4178','fruit','Spartan Apple','small',NULL),
    ('4179','fruit','Spartan Apple','large',NULL),
    ('4180','fruit','Spartan Apple','large',NULL),
    ('4181','fruit','Stayman Apple','small',NULL),
    ('4182','fruit','Sturmer Pippin Apple',NULL,NULL),
    ('4183','fruit','Stayman Apple','large',NULL),
    ('4185','fruit','York Apple','small',NULL),
    ('4186','fruit','Yellow Banana','small',NULL),
    ('4187','fruit','York Apple','large',NULL),
    ('4188','fruit','White Flesh Ready-To-Eat Nectarine','small',NULL),
    ('4189','fruit','Winesap Apple','small',NULL),
    ('4190','fruit','Winesap Apple','small',NULL),
    ('4191','fruit','Winesap Apple','large',NULL),
    ('4192','fruit','Winesap Apple','large',NULL),
    ('4193','fruit','Apple',NULL,NULL),
    ('4194','fruit','Apple',NULL,NULL),
    ('4195','fruit','Apple',NULL,NULL),
    ('4196','fruit','Apple',NULL,NULL),
    ('4197','fruit','Apple',NULL,NULL),
    ('4198','fruit','Apple',NULL,NULL),
    ('4199','fruit','Apple',NULL,NULL),
    ('4200','fruit','Apple',NULL,NULL),
    ('4201','fruit','Apple',NULL,NULL),
    ('4202','fruit','Apple',NULL,NULL),
    ('4203','fruit','Apple',NULL,NULL),
    ('4204','fruit','Apple',NULL,NULL),
    ('4205','fruit','Apple',NULL,NULL),
    ('4206','fruit','Apple',NULL,NULL),
    ('4207','fruit','Apple',NULL,NULL),
    ('4208','fruit','Apple',NULL,NULL),
    ('4209','fruit','Apple',NULL,NULL),
    ('4210','fruit','Apple',NULL,NULL),
    ('4211','fruit','Apple',NULL,NULL),
    ('4212','fruit','Apple',NULL,NULL),
    ('4213','fruit','Apple',NULL,NULL),
    ('4214','fruit','Apple',NULL,NULL),
    ('4215','fruit','Apple',NULL,NULL),
    ('4216','fruit','Apple',NULL,NULL),
    ('4217','fruit','Apple',NULL,NULL),
    ('4218','fruit','Regular Apricot','small',NULL),
    ('4219','fruit','Apricot',NULL,NULL),
    ('4220','fruit','Atemoya',NULL,NULL),
    ('4221','fruit','Green Avocado','small',NULL),
    ('4222','fruit','Green Avocado','small',NULL),
    ('4223','fruit','Green Avocado','large',NULL),
    ('4224','fruit','Green Avocado','large',NULL),
    ('4225','fruit','Hass Avocado','large',NULL),
    ('4226','fruit','Cocktail Avocado',NULL,NULL),
    ('4227','fruit','Avocado',NULL,NULL),
    ('4228','fruit','Avocado',NULL,NULL),
    ('4229','fruit','Burro Banana',NULL,NULL),
    ('4230','fruit','Dominique Banana',NULL,NULL),
    ('4231','fruit','Green Banana',NULL,NULL),
    ('4232','fruit','Leaves Banana',NULL,NULL),
    ('4233','fruit','Manzano Banana',NULL,NULL),
    ('4234','fruit','Baby Banana',NULL,NULL),
    ('4235','fruit','Plantain Banana',NULL,NULL),
    ('4236','fruit','Red Banana',NULL,NULL),
    ('4237','fruit','Banana',NULL,NULL),
    ('4238','fruit','Banana',NULL,NULL),
    ('4239','fruit','Blackberry',NULL,NULL),
    ('4240','fruit','Blueberry',NULL,NULL),
    ('4241','fruit','Boysenberry',NULL,NULL),
    ('4242','fruit','Cranberry',NULL,NULL),
    ('4243','fruit','Gooseberry',NULL,NULL),
    ('4244','fruit','Black Raspberry',NULL,NULL),
    ('4245','fruit','Golden Raspberry',NULL,NULL),
    ('4246','fruit','Strawberry',NULL,NULL),
    ('4251','fruit','Long-Stemmed Strawberry',NULL,NULL),
    ('4252','fruit','Berry',NULL,NULL),
    ('4253','fruit','Berry',NULL,NULL),
    ('4254','fruit','Breadfruit',NULL,NULL),
    ('4255','fruit','Cactus Pear',NULL,NULL),
    ('4256','fruit',' Starfruit',NULL,NULL),
    ('4257','fruit','Cherimoya',NULL,NULL),
    ('4258','fruit','Golden Cherry',NULL,NULL),
    ('4259','fruit','Cherry',NULL,NULL),
    ('4260','fruit','In Husk Coconut',NULL,NULL),
    ('4261','fruit','Husked Coconut',NULL,NULL),
    ('4262','fruit','Coconut',NULL,NULL),
    ('4263','fruit','Fresh Regular Date',NULL,NULL),
    ('4264','fruit','Fresh Date',NULL,NULL),
    ('4265','fruit','Feijoa',NULL,NULL),
    ('4266','fruit','Black Fig',NULL,NULL),
    ('4267','fruit','Brown Fig',NULL,NULL),
    ('4268','fruit','Green Fig',NULL,NULL),
    ('4269','fruit','Fig',NULL,NULL),
    ('4270','fruit','Black Seeded Grape',NULL,NULL),
    ('4271','fruit','Champagne Grape',NULL,NULL),
    ('4272','fruit','Concord Grape',NULL,NULL),
    ('4273','fruit','Red Seeded Grape',NULL,NULL),
    ('4274','fruit','White Seeded Grape',NULL,NULL),
    ('4275','fruit','Grape',NULL,NULL),
    ('4276','fruit','Grape',NULL,NULL),
    ('4277','fruit','Grape',NULL,NULL),
    ('4278','fruit','Grape',NULL,NULL),
    ('4279','fruit','Pummelo',NULL,NULL),
    ('4280','fruit','Red Grapefruit','small',NULL),
    ('4281','fruit','Red Grapefruit','large',NULL),
    ('4282','fruit','Red Grapefruit','large',NULL),
    ('4283','fruit','Red Grapefruit','large',NULL),
    ('4284','fruit','Deep Red Grapefruit','small',NULL),
    ('4285','fruit','Deep Red Grapefruit','small',NULL),
    ('4286','fruit','Deep Red Grapefruit','small',NULL),
    ('4287','fruit','Deep Red Grapefruit','large',NULL),
    ('4288','fruit','Deep Red Grapefruit','large',NULL),
    ('4289','fruit','Deep Red Grapefruit','large',NULL),
    ('4290','fruit','White Grapefruit','small',NULL),
    ('4291','fruit','White Grapefruit','small',NULL),
    ('4292','fruit','White Grapefruit','small',NULL),
    ('4293','fruit','White Grapefruit','large',NULL),
    ('4294','fruit','White Grapefruit','large',NULL),
    ('4295','fruit','White Grapefruit','large',NULL),
    ('4296','fruit','Grapefruit',NULL,NULL),
    ('4297','fruit','Grapefruit',NULL,NULL),
    ('4298','fruit','Grapefruit',NULL,NULL),
    ('4299','fruit','Guava',NULL,NULL),
    ('4300','fruit','Homli Fruit',NULL,NULL),
    ('4301','fruit','Kiwifruit',NULL,NULL),
    ('4302','fruit','Kiwano',NULL,NULL),
    ('4303','fruit','Kumquat',NULL,NULL),
    ('4304','fruit','Lemon',NULL,NULL),
    ('4305','fruit','Key Lime',NULL,NULL),
    ('4306','fruit','Lime',NULL,NULL),
    ('4307','fruit','Longan',NULL,NULL),
    ('4308','fruit','Loquat',NULL,NULL),
    ('4309','fruit','Lychee',NULL,NULL),
    ('4310','fruit','Mamey',NULL,NULL),
    ('4311','fruit','Green Mango','small',NULL),
    ('4312','fruit','Yellow Mango','small',NULL),
    ('4313','fruit','Mango',NULL,NULL),
    ('4314','fruit','Mango',NULL,NULL),
    ('4315','fruit','Mango',NULL,NULL),
    ('4316','fruit','Mango',NULL,NULL),
    ('4317','fruit','Yellow Honeydew Melon',NULL,NULL),
    ('4318','fruit','Cantaloupe Melon','small',NULL),
    ('4319','fruit','Cantaloupe Melon','large',NULL),
    ('4320','fruit','Casaba Melon',NULL,NULL),
    ('4321','fruit','Cinnabar Melon',NULL,NULL),
    ('4322','fruit','Crenshaw Melon',NULL,NULL),
    ('4323','fruit','Strawberry',NULL,NULL),
    ('4324','fruit','French Afternoon Melon',NULL,NULL),
    ('4325','fruit','French Breakfast Melon',NULL,NULL),
    ('4326','fruit','Galia Melon',NULL,NULL),
    ('4327','fruit','Cantaline Melon',NULL,NULL),
    ('4328','fruit','Limequat',NULL,NULL),
    ('4329','fruit','White Honeydew Melon','small',NULL),
    ('4330','fruit','Mayan Melon',NULL,NULL),
    ('4331','fruit','Sugarbaby Melon',NULL,NULL),
    ('4332','fruit','Muskmelon Melon',NULL,NULL),
    ('4333','fruit','Pepino Melon',NULL,NULL),
    ('4334','fruit','Persian Melon',NULL,NULL),
    ('4335','fruit','Prince Melon',NULL,NULL),
    ('4336','fruit','Santa Claus Melon',NULL,NULL),
    ('4337','fruit','Saticoy Melon',NULL,NULL),
    ('4338','fruit','Sharlin Melon',NULL,NULL),
    ('4339','fruit','Spanish Melon',NULL,NULL),
    ('4340','fruit','Yellow Watermelon',NULL,NULL),
    ('4341','fruit','Yellow Seedless Watermelon',NULL,NULL),
    ('4342','fruit','Melon',NULL,NULL),
    ('4377','fruit','Yellow Flesh Ready-To-Eat Nectarine','small',NULL),
    ('4378','fruit','Yellow Flesh Ready-To-Eat Nectarine','large',NULL),
    ('4379','fruit','Nectarine',NULL,NULL),
    ('4380','fruit','Nectarine',NULL,NULL),
    ('4381','fruit','Blood Orange',NULL,NULL),
    ('4382','fruit','Juice Orange',NULL,NULL),
    ('4383','fruit','Minneola Tangelo',NULL,NULL),
    ('4384','fruit','Navel Orange','small',NULL),
    ('4385','fruit','Navel Orange','large',NULL),
    ('4386','fruit','Temple Orange','small',NULL),
    ('4387','fruit','Temple Orange','large',NULL),
    ('4388','fruit','Valencia Orange','large',NULL),
    ('4388','fruit','Valencia Orange','large',NULL),
    ('4389','fruit','Orange',NULL,NULL),
    ('4390','fruit','Orange',NULL,NULL),
    ('4391','fruit','Orange',NULL,NULL),
    ('4392','fruit','Orange',NULL,NULL),
    ('4393','fruit','Orange',NULL,NULL),
    ('4394','fruit','Regular Papaya','large',NULL),
    ('4395','fruit','Cooking Papaya',NULL,NULL),
    ('4396','fruit','Papaya',NULL,NULL),
    ('4397','fruit','Purple Passion Fruit',NULL,NULL),
    ('4398','fruit','Passion Fruit',NULL,NULL),
    ('4399','fruit','Indian Peach',NULL,NULL),
    ('4400','fruit','White Flesh Peach','small',NULL),
    ('4401','fruit','White Flesh Peach','large',NULL),
    ('4402','fruit','Yellow Flesh Peach','small',NULL),
    ('4403','fruit','Yellow Flesh Peach','large',NULL),
    ('4404','fruit','Peach',NULL,NULL),
    ('4405','fruit','Peach',NULL,NULL),
    ('4406','fruit','White Asian Pear',NULL,NULL),
    ('4407','fruit','Yellow Asian Pear',NULL,NULL),
    ('4408','fruit','Brown Asian Pear',NULL,NULL),
    ('4409','fruit','Bartlett Pear','large',NULL),
    ('4410','fruit','Red Bartlett Pear',NULL,NULL),
    ('4411','fruit','Bosc Pear','small',NULL),
    ('4412','fruit','Bosc Pear','large',NULL),
    ('4413','fruit','Bosc Pear','large',NULL),
    ('4414','fruit','Comice Pear',NULL,NULL),
    ('4415','fruit','Red Pear',NULL,NULL),
    ('4416','fruit','Anjou Pear','large',NULL),
    ('4417','fruit','Anjou Red Pear',NULL,NULL),
    ('4418','fruit','Forelle Pear',NULL,NULL),
    ('4419','fruit','French Pear',NULL,NULL),
    ('4420','fruit','King Royal Pear',NULL,NULL),
    ('4421','fruit','Packham''s Triumph Pear',NULL,NULL),
    ('4422','fruit','Seckel Pear',NULL,NULL),
    ('4423','fruit','Tree Ripened Pear',NULL,NULL),
    ('4424','fruit','Winter Nelis Pear',NULL,NULL),
    ('4425','fruit','Pear',NULL,NULL),
    ('4426','fruit','Pear',NULL,NULL),
    ('4427','fruit','Regular Perssimmon',NULL,NULL),
    ('4428','fruit','Japanese Perssimmon',NULL,NULL),
    ('4429','fruit','Perssimmon',NULL,NULL),
    ('4430','fruit','Pineapple','large',NULL),
    ('4431','fruit','Jet Fresh Pineapple','small',NULL),
    ('4432','fruit','Jet Fresh Pineapple','large',NULL),
    ('4433','fruit','Pineapple',NULL,NULL),
    ('4434','fruit','Green Plum','small',NULL),
    ('4435','fruit','Green Plum','large',NULL),
    ('4436','fruit','Italian Prune Plum',NULL,NULL),
    ('4437','fruit','Purple Plum','small',NULL),
    ('4438','fruit','Purple Plum','large',NULL),
    ('4439','fruit','Tree Ripened Plum','small',NULL),
    ('4440','fruit','Tree Ripened Plum','large',NULL),
    ('4441','fruit','Yellow Plum','small',NULL),
    ('4442','fruit','Yellow Plum','large',NULL),
    ('4443','fruit','Plum',NULL,NULL),
    ('4444','fruit','Plum',NULL,NULL),
    ('4445','fruit','Pomegranate','small',NULL),
    ('4446','fruit','Pomegranate',NULL,NULL),
    ('4447','fruit','Quince',NULL,NULL),
    ('4448','fruit','Tamarind',NULL,NULL),
    ('4449','fruit','Sunburst Tangerine',NULL,NULL),
    ('4450','fruit','Clementine  Tangerine',NULL,NULL),
    ('4451','fruit','Dancy Tangerine',NULL,NULL),
    ('4452','fruit','Fairchild Tangerine',NULL,NULL),
    ('4453','fruit','Honey Tangerine',NULL,NULL),
    ('4454','fruit','Kinnow Tangerine',NULL,NULL),
    ('4455','fruit','Royal Tangerine',NULL,NULL),
    ('4456','fruit','Tangelo',NULL,NULL),
    ('4457','fruit','Tangerine',NULL,NULL),
    ('4458','fruit','Tangerine',NULL,NULL),
    ('4459','fruit','Jamaican Tangelo',NULL,NULL),
    ('4491','fruit','Red Grapefruit','extra large',NULL),
    ('4492','fruit','Red Grapefruit','extra large',NULL),
    ('4493','fruit','Red Grapefruit','extra large',NULL),
    ('4494','fruit','Deep Red Grapefruit','extra large',NULL),
    ('4495','fruit','Deep Red Grapefruit','extra large',NULL),
    ('4496','fruit','Deep Red Grapefruit','extra large',NULL),
    ('4497','fruit','Sugraone Grape',NULL,NULL),
    ('4498','fruit','White Seedless Grape',NULL,NULL),
    ('4499','fruit','Crimson Grape',NULL,NULL),
    ('4514','vegetable','Alfalfa Sprout',NULL,NULL),
    ('4515','herb','Florence Bulb Fennel',NULL,NULL),
    ('4516','vegetable','Artichoke','small',NULL),
    ('4517','vegetable','Purple Artichoke','small',NULL),
    ('4518','vegetable','Purple Artichoke','large',NULL),
    ('4519','vegetable','Baby Artichoke',NULL,NULL),
    ('4520','vegetable','Artichoke',NULL,NULL),
    ('4521','vegetable','Green Asparagus','large',NULL),
    ('4522','vegetable','White Asparagus','small',NULL),
    ('4523','vegetable','White Asparagus','large',NULL),
    ('4524','vegetable','Tips Asparagus',NULL,NULL),
    ('4525','vegetable','Asparagus',NULL,NULL),
    ('4526','vegetable','Asparagus',NULL,NULL),
    ('4527','vegetable','Chinese Long Bean',NULL,NULL),
    ('4528','vegetable','Fava Bean',NULL,NULL),
    ('4529','vegetable','Lima Bean',NULL,NULL),
    ('4530','vegetable','Pole Bean',NULL,NULL),
    ('4531','vegetable','Purple Hull Bean',NULL,NULL),
    ('4532','vegetable','Shell Bean',NULL,NULL),
    ('4533','vegetable','Wax Bean',NULL,NULL),
    ('4534','vegetable','Winged Bean',NULL,NULL),
    ('4535','vegetable','Bean',NULL,NULL),
    ('4536','vegetable','Mung Bean Sprout Bean Sprout',NULL,NULL),
    ('4537','vegetable','Baby Golden Beet',NULL,NULL),
    ('4538','vegetable','Baby Red Beet',NULL,NULL),
    ('4539','vegetable','Bunch Beet',NULL,NULL),
    ('4540','vegetable','Loose Beet',NULL,NULL),
    ('4541','vegetable','Beet',NULL,NULL),
    ('4542','vegetable','Beet Green',NULL,NULL),
    ('4543','vegetable','Belgian Endive',NULL,NULL),
    ('4544','vegetable','Baby Pak Choi',NULL,NULL),
    ('4545','vegetable','Pak Choi',NULL,NULL),
    ('4547','vegetable','Chinese Broccoli',NULL,NULL),
    ('4548','vegetable','Florettes Broccoli',NULL,NULL),
    ('4549','vegetable','Broccoli',NULL,NULL),
    ('4550','vegetable','Brussels Sprout',NULL,NULL),
    ('4551','vegetable','Brussels Sprout',NULL,NULL),
    ('4552','vegetable','Chinese Cabbage',NULL,NULL),
    ('4553','fruit','Taylors Gold Pear',NULL,NULL),
    ('4554','vegetable','Red Cabbage',NULL,NULL),
    ('4555','vegetable','Savoy Green Cabbage',NULL,NULL),
    ('4556','vegetable','Cabbage',NULL,NULL),
    ('4557','vegetable','Cabbage',NULL,NULL),
    ('4558','vegetable','Cactus Leave',NULL,NULL),
    ('4559','vegetable','Cardoon',NULL,NULL),
    ('4560','vegetable','Baby Carrot',NULL,NULL),
    ('4561','vegetable','French Carrot',NULL,NULL),
    ('4562','vegetable','Loose Carrot',NULL,NULL),
    ('4563','vegetable','Carrot Sticks Carrot',NULL,NULL),
    ('4564','vegetable','Carrot',NULL,NULL),
    ('4565','vegetable','Carrot',NULL,NULL),
    ('4566','vegetable','Florettes Cauliflower',NULL,NULL),
    ('4567','vegetable','Green Cauliflower',NULL,NULL),
    ('4568','vegetable','Purple Cauliflower',NULL,NULL),
    ('4569','vegetable','Cauliflower',NULL,NULL),
    ('4570','vegetable','Cauliflower',NULL,NULL),
    ('4571','vegetable','Cauliflower',NULL,NULL),
    ('4572','vegetable','Cauliflower','large',NULL),
    ('4573','vegetable','Baby Cauliflower',NULL,NULL),
    ('4575','vegetable','Hearts Celery',NULL,NULL),
    ('4576','vegetable','Celery Sticks Celery',NULL,NULL),
    ('4577','vegetable','Celery',NULL,NULL),
    ('4578','vegetable','Celery',NULL,NULL),
    ('4579','vegetable','Celery',NULL,NULL),
    ('4580','vegetable','Celery',NULL,NULL),
    ('4581','vegetable','Celery',NULL,NULL),
    ('4582','vegetable','Bunch Celery','large',NULL),
    ('4583','vegetable','Bunch Celery','large',NULL),
    ('4584','fruit','Green Mango','large',NULL),
    ('4585','vegetable','Celery Root',NULL,NULL),
    ('4586','vegetable','Green Chard',NULL,NULL),
    ('4587','vegetable','Red Chard',NULL,NULL),
    ('4588','vegetable','Chard',NULL,NULL),
    ('4589','vegetable','Sweet Baby Corn',NULL,NULL),
    ('4590','vegetable','Sweet Bi-Color Corn',NULL,NULL),
    ('4591','vegetable','Corn',NULL,NULL),
    ('4592','vegetable','Armenian Cucumber',NULL,NULL),
    ('4593','vegetable','English Cucumber',NULL,NULL),
    ('4594','vegetable','Japanese Cucumber',NULL,NULL),
    ('4595','vegetable','Lemon Cucumber',NULL,NULL),
    ('4596','vegetable','Pickling Cucumber',NULL,NULL),
    ('4597','vegetable','Cucumber',NULL,NULL),
    ('4598','vegetable','Daikon',NULL,NULL),
    ('4599','vegetable','Baby Eggplant',NULL,NULL),
    ('4600','vegetable','Baby White Eggplant',NULL,NULL),
    ('4601','vegetable','Japanese Eggplant',NULL,NULL),
    ('4602','vegetable','White Eggplant',NULL,NULL),
    ('4603','vegetable','Eggplant',NULL,NULL),
    ('4604','vegetable','Endive',NULL,NULL),
    ('4605','vegetable','Green Escarole',NULL,NULL),
    ('4606','vegetable','Fiddlehead Fern',NULL,NULL),
    ('4607','vegetable','Chinese Mustard',NULL,NULL),
    ('4608','vegetable','Regular Garlic',NULL,NULL),
    ('4609','vegetable','Elephant Garlic',NULL,NULL),
    ('4610','vegetable','Garlic',NULL,NULL),
    ('4611','vegetable','Garlic',NULL,NULL),
    ('4612','vegetable','Regular Ginger Root',NULL,NULL),
    ('4613','vegetable','Ginger Root',NULL,NULL),
    ('4614','vegetable','Collard Green',NULL,NULL),
    ('4615','vegetable','Dandelion Green',NULL,NULL),
    ('4616','vegetable','Mustard Green',NULL,NULL),
    ('4617','vegetable','Polk Green Green',NULL,NULL),
    ('4618','vegetable','Texas Mustard Green',NULL,NULL),
    ('4619','vegetable','Turnip Green',NULL,NULL),
    ('4620','vegetable','Green',NULL,NULL),
    ('4621','vegetable','Green',NULL,NULL),
    ('4622','vegetable','Green',NULL,NULL),
    ('4623','vegetable','Green',NULL,NULL),
    ('4624','vegetable','Green',NULL,NULL),
    ('4625','vegetable','Horseradish Root',NULL,NULL),
    ('4626','vegetable','Jicama Bean',NULL,NULL),
    ('4627','vegetable','Kale',NULL,NULL),
    ('4628','vegetable','Kohlrabi',NULL,NULL),
    ('4629','vegetable','Regular Leek',NULL,NULL),
    ('4630','vegetable','Baby Leek',NULL,NULL),
    ('4631','vegetable','Bibb Lettuce',NULL,NULL),
    ('4632','vegetable','Boston Lettuce',NULL,NULL),
    ('4633','vegetable','Hydroponic Lettuce',NULL,NULL),
    ('4634','vegetable','Iceberg Lettuce',NULL,NULL),
    ('4635','fruit','Red Seedless Grape',NULL,NULL),
    ('4636','fruit','Red Globe Grape',NULL,NULL),
    ('4637','fruit','Red Seeded Grape',NULL,NULL),
    ('4638','fruit','Fantasy Grape',NULL,NULL),
    ('4639','vegetable','Mache Lettuce',NULL,NULL),
    ('4640','vegetable','Romaine Lettuce',NULL,NULL),
    ('4641','vegetable','Lettuce',NULL,NULL),
    ('4642','vegetable','Lettuce',NULL,NULL),
    ('4643','vegetable','Lettuce',NULL,NULL),
    ('4644','vegetable','Malanga',NULL,NULL),
    ('4645','vegetable','Regular Button Mushroom','small',NULL),
    ('4646','vegetable','Black Forest Mushroom',NULL,NULL),
    ('4647','vegetable','Chanterelle Mushroom',NULL,NULL),
    ('4648','vegetable','Cremini Brown Mushroom',NULL,NULL),
    ('4649','vegetable','Oyster Mushroom',NULL,NULL),
    ('4650','vegetable','Portabella Mushroom',NULL,NULL),
    ('4651','vegetable','Shiitake Mushroom',NULL,NULL),
    ('4652','vegetable','Wood Ear Mushroom',NULL,NULL),
    ('4653','vegetable','Mushroom',NULL,NULL),
    ('4654','vegetable','Mushroom',NULL,NULL),
    ('4655','vegetable','Regular Okra',NULL,NULL),
    ('4656','vegetable','Chinese Okra',NULL,NULL),
    ('4657','vegetable','Red Okra',NULL,NULL),
    ('4658','vegetable','Boiling Onion',NULL,NULL),
    ('4659','vegetable','Bulb Onion',NULL,NULL),
    ('4660','vegetable','Pearl Onion',NULL,NULL),
    ('4661','vegetable','White Pickling Onion',NULL,NULL),
    ('4662','vegetable','Shallots Onion',NULL,NULL),
    ('4663','vegetable','White Onion',NULL,NULL),
    ('4664','vegetable','Red Regular Tomato',NULL,NULL),
    ('4665','vegetable','Brown Onion','small',NULL),
    ('4666','vegetable','Onion',NULL,NULL),
    ('4667','vegetable','Onion',NULL,NULL),
    ('4668','vegetable','Onion',NULL,NULL),
    ('4669','vegetable','Onion',NULL,NULL),
    ('4670','vegetable','Onion',NULL,NULL),
    ('4671','vegetable','Parsley Root',NULL,NULL),
    ('4672','vegetable','Parsnip',NULL,NULL),
    ('4673','vegetable','Blackeyed Pea',NULL,NULL),
    ('4674','vegetable','Green Pea',NULL,NULL),
    ('4675','vegetable','Sugar Snap Pea',NULL,NULL),
    ('4676','vegetable','Pea',NULL,NULL),
    ('4677','vegetable','Anaheim Pepper',NULL,NULL),
    ('4678','vegetable','Banana Pepper',NULL,NULL),
    ('4679','vegetable','Field Grown Brown Bell Pepper',NULL,NULL),
    ('4680','vegetable','Field Grown Yellow Bell Pepper',NULL,NULL),
    ('4681','vegetable','Field Grown Green Bell Pepper','small',NULL),
    ('4682','vegetable','Field Grown Orange Bell Pepper',NULL,NULL),
    ('4683','vegetable','Field Grown Purple Bell Pepper',NULL,NULL),
    ('4684','vegetable','Field Grown White Bell Pepper',NULL,NULL),
    ('4685','vegetable','Chili Dried Pepper',NULL,NULL),
    ('4686','vegetable','Chili Green Pepper',NULL,NULL),
    ('4687','vegetable','Cubanelle Pepper',NULL,NULL),
    ('4688','vegetable','Greenhouse Red Bell Pepper',NULL,NULL),
    ('4689','vegetable','Greenhouse Yellow Bell Pepper',NULL,NULL),
    ('4690','vegetable','Hungarian Hot Pepper',NULL,NULL),
    ('4691','vegetable','Hot Mixed Pepper',NULL,NULL),
    ('4692','vegetable','Hungarian Wax Pepper',NULL,NULL),
    ('4693','vegetable','Jalapeno Green Pepper',NULL,NULL),
    ('4694','vegetable','Jalapeno Red Pepper',NULL,NULL),
    ('4695','vegetable','Japanese Red Pepper',NULL,NULL),
    ('4696','vegetable','Green Long Hot Pepper',NULL,NULL),
    ('4697','vegetable','Red Long Hot Pepper',NULL,NULL),
    ('4698','vegetable','Morita Chili Pepper',NULL,NULL),
    ('4699','vegetable','Negro Pepper',NULL,NULL),
    ('4700','vegetable','New Mexico Pepper',NULL,NULL),
    ('4701','vegetable','Green Pasilla Pepper',NULL,NULL),
    ('4702','vegetable','Red Pasilla Pepper',NULL,NULL),
    ('4703','vegetable','Pasilla Pod Pepper',NULL,NULL),
    ('4704','vegetable','Pinole Pepper',NULL,NULL),
    ('4705','vegetable','Poblano Pepper',NULL,NULL),
    ('4706','vegetable','Red Cheese Pepper',NULL,NULL),
    ('4707','vegetable','Red Finger Pepper',NULL,NULL),
    ('4708','vegetable','Red Pimiento Pepper',NULL,NULL),
    ('4709','vegetable','Serrano Pepper',NULL,NULL),
    ('4710','vegetable','Pepper',NULL,NULL),
    ('4711','vegetable','Pepper',NULL,NULL),
    ('4712','vegetable','Pepper',NULL,NULL),
    ('4713','vegetable','Pepper',NULL,NULL),
    ('4714','vegetable','Pepper',NULL,NULL),
    ('4715','vegetable','Pepper',NULL,NULL),
    ('4716','vegetable','Pepper',NULL,NULL),
    ('4717','vegetable','Pepper',NULL,NULL),
    ('4718','vegetable','Pepper',NULL,NULL),
    ('4719','vegetable','Pepper',NULL,NULL),
    ('4720','vegetable','Pepper',NULL,NULL),
    ('4721','vegetable','Pepper',NULL,NULL),
    ('4722','vegetable','Pepper',NULL,NULL),
    ('4723','vegetable','Red Creamer Potato',NULL,NULL),
    ('4724','vegetable','White Creamer Potato',NULL,NULL),
    ('4725','vegetable','Russet Potato',NULL,NULL),
    ('4726','vegetable','White Long Potato',NULL,NULL),
    ('4727','vegetable','Yellow Potato',NULL,NULL),
    ('4728','vegetable','Potato',NULL,NULL),
    ('4729','vegetable','Potato',NULL,NULL),
    ('4730','vegetable','Potato',NULL,NULL),
    ('4731','vegetable','Potato',NULL,NULL),
    ('4732','vegetable','Potato',NULL,NULL),
    ('4733','vegetable','Potato',NULL,NULL),
    ('4734','vegetable','Mini Pumpkin',NULL,NULL),
    ('4735','vegetable','Regular Pumpkin',NULL,NULL),
    ('4736','vegetable','Pumpkin',NULL,NULL),
    ('4737','vegetable','Pumpkin',NULL,NULL),
    ('4738','vegetable','Radicchio',NULL,NULL),
    ('4739','vegetable','Black Radish',NULL,NULL),
    ('4740','vegetable','Bunched White Radish',NULL,NULL),
    ('4741','vegetable','Italian Red Radish',NULL,NULL),
    ('4742','vegetable','Red Radish',NULL,NULL),
    ('4743','vegetable','White Radish',NULL,NULL),
    ('4744','vegetable','Radish',NULL,NULL),
    ('4745','vegetable','Regular Rhubarb',NULL,NULL),
    ('4746','vegetable','Rhubarb',NULL,NULL),
    ('4747','vegetable','Regular Rutabaga',NULL,NULL),
    ('4748','vegetable','Rutabaga',NULL,NULL),
    ('4749','vegetable','Spinach',NULL,NULL),
    ('4750','vegetable','Acorn Squash',NULL,NULL),
    ('4751','vegetable','Golden Acorn Squash',NULL,NULL),
    ('4752','vegetable','Swan White Acorn Squash',NULL,NULL),
    ('4753','vegetable','Australian Blue Squash',NULL,NULL),
    ('4754','vegetable','Baby Scallopini Squash',NULL,NULL),
    ('4755','vegetable','Baby Summer Squash',NULL,NULL),
    ('4756','vegetable','Baby Green Zucchini',NULL,NULL),
    ('4757','vegetable','Banana Squash',NULL,NULL),
    ('4758','vegetable','Buttercup Squash',NULL,NULL),
    ('4759','vegetable','Butternut Squash',NULL,NULL),
    ('4760','vegetable','Calabaza Squash',NULL,NULL),
    ('4761','vegetable','Chayote',NULL,NULL),
    ('4762','vegetable','Artichoke','extra large',NULL),
    ('4763','vegetable','Delicata Squash',NULL,NULL),
    ('4764','vegetable','Dumpling Squash',NULL,NULL),
    ('4765','vegetable','Gem Squash',NULL,NULL),
    ('4766','vegetable','Golden Delicious Squash',NULL,NULL),
    ('4767','vegetable','Golden Nugget Squash',NULL,NULL),
    ('4768','vegetable','Hubbard Squash',NULL,NULL),
    ('4769','vegetable','Kabocha Squash',NULL,NULL),
    ('4770','fruit','Hass Avocado',NULL,NULL),
    ('4771','fruit','Green Avocado','medium ',NULL),
    ('4772','vegetable','Yellow Chili Pepper',NULL,NULL),
    ('4773','vegetable','Patty Pan Squash',NULL,NULL),
    ('4774','vegetable','Red Kuri Squash',NULL,NULL),
    ('4775','vegetable','Scallopini Squash',NULL,NULL),
    ('4776','vegetable','Spaghetti Squash',NULL,NULL),
    ('4777','vegetable','Sunburst Squash',NULL,NULL),
    ('4778','vegetable','Regular Yellow Tomato',NULL,NULL),
    ('4779','vegetable','Sweet Mama Squash',NULL,NULL),
    ('4780','vegetable','Turban Squash',NULL,NULL),
    ('4781','vegetable','White Squash',NULL,NULL),
    ('4782','vegetable','Straightneck Squash',NULL,NULL),
    ('4783','vegetable','Foo Qua Bitter Melon',NULL,NULL),
    ('4784','vegetable','Crookneck Squash',NULL,NULL),
    ('4785','vegetable','Squash',NULL,NULL),
    ('4786','vegetable','Squash',NULL,NULL),
    ('4787','vegetable','Squash',NULL,NULL),
    ('4788','vegetable','Squash',NULL,NULL),
    ('4789','vegetable','Squash',NULL,NULL),
    ('4790','vegetable','Sugar Cane',NULL,NULL),
    ('4791','vegetable','Sunchoke',NULL,NULL),
    ('4792','vegetable','Golden Tamarillo',NULL,NULL),
    ('4793','vegetable','Red Tamarillo',NULL,NULL),
    ('4794','vegetable','Taro Root','small',NULL),
    ('4795','vegetable','Taro Root','large',NULL),
    ('4796','vegetable','Red Cherry Tomato',NULL,NULL),
    ('4797','vegetable','Yellow Cherry Tomato',NULL,NULL),
    ('4798','vegetable','Greenhouse Red Tomato','small',NULL),
    ('4799','vegetable','Greenhouse Red Tomato','large',NULL),
    ('4800','vegetable','Home Grown Tomato',NULL,NULL),
    ('4801','vegetable','Tomatillo',NULL,NULL),
    ('4802','vegetable','Dried Tomato',NULL,NULL),
    ('4803','vegetable','Red Teardrop Tomato',NULL,NULL),
    ('4804','vegetable','Yellow Teardrop Tomato',NULL,NULL),
    ('4805','vegetable','Regular Red Tomato','small',NULL),
    ('4806','vegetable','Tomato',NULL,NULL),
    ('4807','vegetable','Tomato',NULL,NULL),
    ('4808','vegetable','Tomato',NULL,NULL),
    ('4809','vegetable','Baby Turnip',NULL,NULL),
    ('4810','vegetable','Bunch Turnip',NULL,NULL),
    ('4811','vegetable','Purple Top Turnip',NULL,NULL),
    ('4812','vegetable','White Turnip',NULL,NULL),
    ('4813','vegetable','Turnip',NULL,NULL),
    ('4814','vegetable','Water Chestnut',NULL,NULL),
    ('4815','vegetable','Watercress',NULL,NULL),
    ('4816','vegetable','Golden Sweet Potato',NULL,NULL),
    ('4817','vegetable','Red Flesh Sweet Potato','large',NULL),
    ('4818','vegetable','Ñame',NULL,NULL),
    ('4819','vegetable','Cassava',NULL,NULL),
    ('4860','dried_fruit','Dried  Apple Slice',NULL,NULL),
    ('4861','dried_fruit','Dried Apricot',NULL,NULL),
    ('4862','dried_fruit','Dried Date',NULL,NULL),
    ('4863','dried_fruit','Dried Date',NULL,NULL),
    ('4864','dried_fruit','Dried Pineapple',NULL,NULL),
    ('4865','dried_fruit','Regular Dried Prune',NULL,NULL),
    ('4866','dried_fruit','Pitted Dried Prune',NULL,NULL),
    ('4867','dried_fruit','Dried Prune',NULL,NULL),
    ('4868','dried_fruit','Black Dried Raisin',NULL,NULL),
    ('4869','dried_fruit','Yellow Dried Raisin',NULL,NULL),
    ('4884','herb','Arugula',NULL,NULL),
    ('4885','herb','Basil',NULL,NULL),
    ('4886','herb','Opal Basil',NULL,NULL),
    ('4887','herb','Sweet Basil',NULL,NULL),
    ('4888','herb','Chive',NULL,NULL),
    ('4889','herb','Cilantro',NULL,NULL),
    ('4890','fruit','Chinese Yali Pear',NULL,NULL),
    ('4891','herb','Dill',NULL,NULL),
    ('4892','herb','Baby Dill',NULL,NULL),
    ('4893','herb','Pickling Dill',NULL,NULL),
    ('4894','herb','Lemongrass',NULL,NULL),
    ('4895','herb','Marjoram',NULL,NULL),
    ('4896','herb','Mint',NULL,NULL),
    ('4897','herb','Oregano',NULL,NULL),
    ('4898','herb','Oyster Plant',NULL,NULL),
    ('4899','herb','Regular Parsley',NULL,NULL),
    ('4901','herb','Italian Parsley',NULL,NULL),
    ('4902','herb','Parsley',NULL,NULL),
    ('4903','herb','Rosemary',NULL,NULL),
    ('4904','herb','Sage',NULL,NULL),
    ('4905','herb','Sorrel',NULL,NULL),
    ('4906','herb','Tarragon',NULL,NULL),
    ('4907','herb','Thyme',NULL,NULL),
    ('4908','herb','Vanilla Bean',NULL,NULL),
    ('4924','nut','Almond',NULL,NULL),
    ('4925','nut','Almond',NULL,NULL),
    ('4926','nut','Brazilnut',NULL,NULL),
    ('4927','nut','Chestnut',NULL,NULL),
    ('4928','nut','Cobnut',NULL,NULL),
    ('4929','nut','Mixed Nuts',NULL,NULL),
    ('4930','nut','Peanut',NULL,NULL),
    ('4931','nut','Raw Peanut',NULL,NULL),
    ('4932','nut','Roasted Salted Peanut',NULL,NULL),
    ('4933','nut','Roasted Unsalted Peanut',NULL,NULL),
    ('4934','nut','Peanut',NULL,NULL),
    ('4935','nut','Peanut',NULL,NULL),
    ('4936','nut','Pecan',NULL,NULL),
    ('4937','nut','Pecan',NULL,NULL),
    ('4938','nut','Pine Nut',NULL,NULL),
    ('4939','nut','Natural Pistachio',NULL,NULL),
    ('4940','nut','Red Pistachio',NULL,NULL),
    ('4941','nut','Pistachio',NULL,NULL),
    ('4942','nut','Sunflower Seed',NULL,NULL),
    ('4943','nut','Regular Walnut',NULL,NULL),
    ('4944','nut','Black Walnut',NULL,NULL),
    ('4945','nut','White Walnut',NULL,NULL),
    ('4946','nut','Walnut',NULL,NULL),
    ('4957','fruit','Black Seeded Grape',NULL,NULL),
    ('4958','fruit','Lemon','medium',NULL),
    ('4959','fruit','Red Mango','large',NULL),
    ('4960','fruit','Fragrant Pear',NULL,NULL),
    ('4961','fruit','Yellow Mango','large',NULL);

