name: CICD Workflow
on:
  release:
    types:
      - "published"
env:
  REGION: eu-west-1
  CDK_VERSION: "1.86.0"
jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: CDK Installation
        run: |
          sudo npm i -g aws-cdk@${{ env.CDK_VERSION }}
          cdk --version
      - name: Install dependencies & Build
        run: |
          npm i
          npm run build
      - name: CDK Apply
        run: |
          cdk bootstrap
          cdk synth
          cdk diff
          cdk deploy \* --require-approval never